### PR TITLE
Move TAP 15 to Accepted

### PR DESCRIPTION
**Pull request by mnm678**
As discussed in the community meeting, this pr proposes moving TAP 15 to accepted.

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
Why SHA2-256? Then again, why do we use that to fix keyids? Might as well fix that everywhere or nowhere. So we can punt this issue.

**Review by joshuagl — APPROVED** [review]
I approve marking this TAP as Accepted.

> Why SHA2-256?
That's what we're already using for hashed bin delegations, see `[path_hash_prefixes](https://theupdateframework.github.io/specification/latest/#path_hash_prefixes)`

We really need to better document hashed bin delegation in the spec, should I file an issue on the spec repo?

**Comment by mnm678** [comment]
> We really need to better document hashed bin delegation in the spec, should I file an issue on the spec repo?

Yes, that would be helpful, thanks. I find myself directing people to PEP 458 to explain this rather than the spec.

**Review by joshuagl — DISMISSED** [review]

**Comment by lukpueh** [comment]
Needs rebasing on top of just merged https://github.com/theupdateframework/taps/pull/155. I'd like to submit the discussed follow-up (https://github.com/theupdateframework/taps/pull/155#discussion_r899977971) early next week.

But I'm fine with accepting TAP 15 before that.

**Comment by joshuagl** [comment]
Could we update the "Augmented Reference Implementation" section to point to the merged implementation? https://github.com/theupdateframework/python-tuf/pull/2010

We should also link to some documentation in python-tuf once we have it

**Review by lukpueh — CHANGES_REQUESTED** [review]
@mnm678, did you really rebase? There is a merge commit in your feature branch now. Also, there still is a conflict.

**Review by lukpueh — APPROVED** [review]

**Review by joshuagl — APPROVED** [review]

**Pull request merged**
