### PR TITLE
Assign a TAP number to candidate-keyid-tap

### LINKED ISSUE #114: Assign # to keyid flexibility TAP?
Now that #112 has been merged, should `candidate-keyid-tap.md` get a number and go into the list/index in the README?

### PR DESCRIPTION
**Pull request by mnm678**
Fixes #114 

Assigns a TAP number to the Draft TAP in accordance with the workflow laid out in [TAP 1](https://github.com/theupdateframework/taps/blob/master/tap1.md).

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
@mnm678 Where is tap12.md tho?

**Comment by mnm678** [comment]
> @mnm678 Where is tap12.md tho?

@trishankatdatadog Github shows the renamed file inline with the old name

**Comment by trishankatdatadog** [comment]
Shouldn't we rename [this](https://github.com/theupdateframework/taps/blob/master/candidate-keyid-tap.md) to `tap12.md`?

**Comment by mnm678** [comment]
Yes, I see [this](https://github.com/theupdateframework/taps/blob/c1c1853a3236191fb0d9c96d6a80e0883d70ba7d/tap12.md) in my commit as tap 12.

**Comment by trishankatdatadog** [comment]
My bad, I missed it. Thanks!

**Pull request merged**
