### PR TITLE
Recommended changes to TAP 4

### PR DESCRIPTION
**Pull request by jhdalek55**
There were a number of comments on the Google Doc. I did not want to
embed them into the text, so I am going to send them either via e-mail
or as a comment on the pull request

### CODE REVIEW

**Comment by vladimir-v-diaz** [comment]
I prefer we add the Google Docs comments as in-line comments in the pull request.

**Comment by jhdalek55** [comment]
Comments that are more than wording changes that I could not indicate in the text--

_The first paragraph under "specification:_" Is the purpose of this TAP  just  FINDING a file on specific repo, or is it about securely verifying and downloading files from two or more repos? If its just about  looking for a file, is there a risk?--and what then why then would you need multiple signatures if you are not dowloading the file? Isn't the idea of this to make sure the file has not been tampered with? I think this paragraph really needs to take in the broader purpose of what this TAP wants to do.

Also the first two sentences back to back in this paragraph do not follow each other. How does finding a target lead to a compromise? It seems like a sentence is needed between these two thoughts.

The 4th paragraph under "The Map File" subhead...Why are there three bullet points if there are only two keys named?

In the first bullet--what does "target paths of patterns" mean. What are the patterns you are referring to here?

Under "Backwards Compatilbility"--it says "however older clients will not utilize the map file and so will ignore this TAP." If we are arguing that you don't need to use the MAP file to secure multiple repos, then don't you want to make the case that a  client can still perform these actions with another file system?

**Comment by jhdalek55** [comment]
I guess I can re-do it that way if you want.

Lois

**Comment by vladimir-v-diaz** [comment]
It's okay.  I can work with these comments here.

**Comment by jhdalek55** [comment]
Thanks, Vlad.

**Comment by vladimir-v-diaz** [comment]
> In the first bullet--what does "target paths of patterns" mean. What are the patterns you are referring to here?

It is the filename paths listed under the "paths" entry in the map file.  Here is the example used in the TAP:

> // Map any target matching *Django* to both Django and PyPI.
>       "paths":        [`*django*`],
>       "repositories": ["Django", "PyPI"],

`*django*` is an example of a filename with wildcard characters.  `users/lois/tap*.md` is another example. 
 This style of filename path is referred to as a glob pattern.  The [Wikipedia page on Glob patterns](https://en.wikipedia.org/wiki/Glob_(programming)) contains more useful information.

**Comment by vladimir-v-diaz** [comment]
> The first paragraph under "specification:" Is the purpose of this TAP just FINDING a file on specific repo, or is it about securely verifying and downloading files from two or more repos? If its just about looking for a file, is there a risk?--and what then why then would you need multiple signatures if you are not dowloading the file? Isn't the idea of this to make sure the file has not been tampered with? I think this paragraph really needs to take in the broader purpose of what this TAP wants to do.

Clients do eventually download the target file from a single repository, but they must also download metadata about the target from one or more repositories to ensure that there is a repository consensus on the entrusted target.  The number of repositories that must be queried to download the same metadata about a target file depends on the rules specified in the map file (or the equivalent).

**Comment by vladimir-v-diaz** [comment]
I will try to directly address your remaining comments in tap4.md

**Comment by jhdalek55** [comment]
After speaking to Justin yesterday, I was going to make some additional edits this morning. I see the branch has not been merged, so should I make these changes on the same branch? Or start a new one?

Lois

**Comment by vladimir-v-diaz** [comment]
Yup, additional edits to the text should be made to the same branch.  I will see any follow-on edits on this pull request.

**Comment by jhdalek55** [comment]
Cool. So when I finish my changes, I just commit? I don't need to do another pull request. Great. Thanks.

Lois

**Comment by vladimir-v-diaz** [comment]
> So when I finish my changes, I just commit? I don't need to do another pull request.

Yes.  Any new commits will should show up here:
https://github.com/theupdateframework/taps/pull/64/commits

**Comment by vladimir-v-diaz** [comment]
> The 4th paragraph under "The Map File" subhead...Why are there three bullet points if there are only two keys named?

The map file contains two top-level dict keys, named "repositories" and "mapping".  The bullets points you refer to are specifically for the "mapping" key, which can contain the "paths", "repositories", and "terminating" (optionally) keys.  The bullet points cover all of the potential keys that "mapping" can contain, but the "terminating" is optional.  Notice that the last entry in the example only contains  the "paths" and "repositories" keys.  I think this is the reason why the text says, "at least two keys."

I quote the text below:

> The value of the "mapping" key is a priority-ordered list that maps paths (i.e., target names) to the specific repositories. Every entry in this list is a dictionary with at least **two** keys:

**Comment by vladimir-v-diaz** [comment]
Note: I made a commit to your pull request to edit the title.  Notice how it appears under the "commits" tab.
https://github.com/theupdateframework/taps/pull/64/commits

You will need to re-sync with the branch/pull request to make any new commits of your own.

**Comment by jhdalek55** [comment]
I have been working on the file and have made a number of changes. If I
sync up before I commit, will I lose the changes i'm made in the file?

**Comment by vladimir-v-diaz** [comment]
No, Git will attempt to automatically merge your changes with mine. If there are merge conflicts, it will let you know.  However, you shouldn't get any merge conflicts because I have modified a part of the file that you unlikely modified as well.

I recommend that you first commit your local changes and sync after.

**Pull request merged**
